export { default as Hero } from './Hero'
export { default as GameOverview } from './GameOverview'
export { default as Features } from './Features'
export { default as MediaSection } from './MediaSection'
export { default as CTASection } from './CTASection'
